#!/bin/sh

# For whatever reason, Tor appears to drop root before configuring /dev/pf for transproxy

# PROVIDE: tor_pf_perms
# REQUIRE: jail
# BEFORE:  tor

. /etc/rc.subr

name="tor_pf_perms"
desc="Modify /dev/pf permissions so that Tor TransPort starts correctly"
rcvar="${name}_enable"
start_cmd="${name}_start"

tor_pf_perms_start() {
	chgrp _tor /dev/pf
	chmod g+rw /dev/pf	
}

load_rc_config $name
run_rc_command "$1"
