
:validate_param_memsize:
MEMSIZE < %s > (%s bytes)
is greater than avail memory < %s bytes > 
/END/

:validate_param_mtu:
%s < %s > is outside of sanity bounds: %s to %s
/END/

:validate_param_ipv4:
Cell < %s > IPV4 < %s > is currently in use inside its gateway < %s >
/END/

:validate_param_ipv42:
Cell < %s > IPV4 < %s > is already reserved by a sibling gateway client < %s > 
/END/

:validate_cellname:
%s < %s > already exists
/END/

