:_generic:
%s
/END/

:w:_generic:
%s
/END/

:_internal0:
Internal bug: set_ctx() is missing positional parameter(s)
/END/

:_internal1:
Internal bug: Invalid getopts
/END/

:_internal2:
Internal bug: Invalid value < %s > passed to function < %s >
/END/

:_internal3:
Internal bug: Non-integer < %s > passed to assert_int_comparison()
/END/

:_internal4:
Internal bug: Mismatch between $1 provided (_cell), and _pfx value
/END/

