
:is_path_exist:
Path < %s > not found
/END/

:is_zfs_exist:
ZFS dataset < %s > not found
/END/

:is_cell_running:
cell: < %s > is not running
/END/

:query_user_response:
User did not respond with affirmative confirmation
/END

:query_cell_type:
Cell < %s > has invalid CLASS < %s >
/END/

:query_cell_param:
Failed to find param < %s > for cell < %s >
/END/

:query_cell_clients:
Failed to find any clients for cell < %s >
/END/

:query_cell_shell:
Failed to find shell for cell < %s >
/END/

:query_sysmem:
Failed to find "avail memory" in dmesg.boot
/END/

:xfail:
Failed to get xprop %s for XID < %s >
/END/

:query_xwin_cellname:
Failed to get cellname for XID < %s > 
/END/

:_resolve_popup_dimensions:
Failed to get 
/END/

:_resolve_popup_fontsize:

/END/
