R_ZFS="zroot/qubsd"
U_ZFS="zusr"
AUTOSNAP="false"
AUTOSTART="false"
BACKUP="false"
CONTROL="none"
ENVSYNC="0zusr"
GATEWAY="none"
# Recommend no default MTU. System already defaults to 1500. Focus on gateways, especially
# wireguard. Clients receive auto adjustment downwards to never exceed the gateway MTU.
#MTU=""
NO_DESTROY="true"
PPT="none"
