#!/bin/sh                                                                                           
                                                                                                    
# PROVIDE: quBSD_VM_boot                                                                            
# REQUIRE: netif jail                                                                               
                                                                                                    
. /etc/rc.subr                                                                                      
                                                                                                    
name="quBSD_VM_boot"                                                                                
desc="Calls the VM startup script at /vmusr/.qubsd-vm-startup ; or on host /zusr/<VM>"              
rcvar="${name}_enable"                                                                              
start_cmd="${name}_start"                                                                           
                                                                                                    
quBSD_VM_boot_start() {                                                                             
        zpool list vmusr > /dev/null 2>&1 || zpool import -f vmusr                                  
        /bin/sh /vmusr/.qubsd-vm-startup                                                            
}                                                                                                   
                                                                                                    
load_rc_config $name                                                                                
run_rc_command "$1"
