#!/bin/sh

# PROVIDE: qb_autostart
# REQUIRE: jail qb_cleanup

. /etc/rc.subr

name="qb_autostart"
desc="Automatically starts jails flagged with autostart in qubsd.conf"
rcvar="${name}_enable"
start_cmd="${name}_start"

qb_autostart_start() {
	# Start all jails tagged with autostart
	/bin/sh /usr/local/libexec/qubsd/qb-start -a > /dev/null 2>&1 &
}

load_rc_config $name
run_rc_command "$1"
