#!/bin/sh

# PROVIDE: qubsd-init
# BEFORE: FILESYSTEMS
# REQUIRE: zfs zvol

. /etc/rc.subr

name="qubsd_init"
desc="Ensures /zusr datasets are imported/mounted, and /overlay files symlinked"
rcvar="${name}_enable"
start_cmd="${name}_start"

qubsd_init_start() {
  # Make sure the zpool is mounted. If there is none, then dont run overlay or users
  if ! zpool list zusr > /dev/null 2>&1 ; then 
    zpool import -f zusr || return 0
  fi

  # Grab all overlay files and linke them to their corresponding locations
  for _file in $(find "/overlay" -type f | sed "s:/overlay::") ; do

    if [ -d "$(dirname $_file)" ] ; then
      chflags noschg "$(dirname $_file)"
      [ -e "$_file" ] && chflags noschg $_file

    else
      mkdir -p $(dirname $_file)
    fi

    ln -sf /overlay${_file} $_file
  done

  # Create the users listed in the zusr /home
  for _dir in $(find "/home" -type d | sed "s:/home::") ; do
    pw useradd -n $_dir -d /home/$_dir -s /bin/csh -m
  done
}

load_rc_config $name
run_rc_command "$1"
