#!/bin/sh

# PROVIDE: qubsd_dhcp 
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="qubsd_dhcp"
desc="Manages dhclient and pf tables for interfaces placed in /tmp/qubsd_dhcp by the host"
rcvar="qubsd_dhcp_enable"
command="/usr/local/bin/${name}"
pidfile="/var/run/${name}.pid"
procname="/bin/sh"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

qubsd_dhcp_stop() {
	rm $pidfile	
}

qubsd_dhcp_start() {
	/usr/sbin/daemon -p ${pidfile} ${command} ${pidfile}
}

load_rc_config $name
run_rc_command "$1"
