#!/bin/sh

. $QCOMMON

trap_init

parse_args() {
    local _fn="parse_args" _opts OPTARG OPTIND
    while getopts dhs: _opts ; do case $_opts in
        d) DESTROY=true ;;
        h) WARN usage ; cat $ERR ; exit 0 ;;
        s) TTL="$OPTARG" ; assert_optarg || eval $(THROW $?) ;;
        *) exit 1 ;;
    esac ; done ; shift $(( OPTIND - 1 ))

    # Must provide [-d] and/or [-t]
    [ -z "$DESTROY" ] && [ -z "$TTL" ] && eval $(THROW 4 $_fn)

    # Sanitize TTL
    [ "$TTL" ] && { assert_time_format "$TTL" || eval $(THROW $? ${_fn}_2) ;}

    # Convenience globals
    DATE=$(date +%s)
}

calculate_snap_suffix() {
    local _fn="calculate_snap_suffix" _date

    # Use the TTL timeframe for modifying the snapname
    case ${TTL##*[0-9]} in
        s) _date='+%b%d_%H%M' ;;
        m) _date='+%b%d_%H%M' ;;
        H) _date='+%b%d_%H_H' ;;
        D) _date='+%b%d_%H_D' ;;
        W) _date='+%b%d_%H_W' ;;
        M) _date='+%Y_%b%d_M' ;;
        Y) _date='+%Y_%b%d_Y' ;;
    esac
    echo $(date $_date)  # Snap will have this @name
}

calculate_destroy_date() {
    local _fn="calculate_destroy_date"

    case ${_ttl##*[0-9]} in
        s) _mult="1" ;;
        m) _mult="60" ;;
        H) _mult="3600" ;;
        D) _mult="3600*24" ;;
        W) _mult="3600*24*7" ;;
        M) _mult="3600*24*31" ;;
        Y) _mult="3600*24*365" ;;
        *) return 1 ;;
    esac
    echo "(${_ttl%?} * $_mult) + $_crea_unix" | bc  # Final destroy date in unix time
}

compose_thin_old_snaps_cmds() {
    local _fn="compose_thin_old_snaps_cmds"
    local _rsnaps _psnaps _snapshots _snap _clones _ttl _integer _creation _crea_unix _destroy _CMDS

    # Most snaps should already be in the cache, but query_*snaps greps and hydrates if necessary
    _class=$(ctx_get ${_pfx}CLASS)
    # Only rootenvs will have root-dataset snapshots
    if [ "$_r_dset" ] && [ "$_class" ] && [ -z ${_class##root*} ] ; then
        query_rootsnaps $_r_dset
        _rsnaps=$(echo "$ROOTSNAPS" | grep -E "^$_r_dset@")
    fi
    # Even rootenvs typically have a persistent dataset. However, skip disp cells.
    if [ "$_p_dset" ] && [ "$_class" ] && [ -n "${_class#disp*}" ] ; then
        query_persistsnaps $_p_dset
        _psnaps=$(echo "$PERSISTSNAPS" | grep -E "^$_p_dset@")
    fi
    _snapshots="$(echo "$_rsnaps" ; echo "$_psnaps")"

    # Resolve each line's destroy date, and add to the list if old
    while IFS= read -r _line ; do
        [ -z "$_line" ] && continue   # Some lines are blank. Ignore/continue
        _snap=$(echo $_line | awk '{print $1}')
        _clones=$(echo $_line | awk '{print $9}')
        _ttl=$(echo $_line | awk '{print $8}')
        _creation=$(echo "$_line" | awk '{print $3, $4, $5, $6, $7}')
        _crea_unix=$(date -j -f "%a %b %d %H:%M %Y" "$_creation" +"%s")
        _destroy=$(calculate_destroy_date)

        # Final command addition. Mute the comparison to not pollute $ERR
        mute assert_int_comparison -G $_destroy -- $DATE && [ "$_clones" = "-" ] \
            && append _CMDS "hush zfs destroy $_snap"
    done << EOF
$_snapshots
EOF

    emit_cmds "$_CMDS"
}

compose_zfs_commands() {
    local _fn="compose_zfs_commands" _class _autosnaps _suffix _r_dset _p_dset _r_snaps _p_snaps _pfx="t_"

    query_qconf_cells_and_paths     # Populate globals: $CELLS and $CELLS_QPATHS
    query_zfs_recursive_defaults    # Sets global DATASETS. Prevents repeat/excess zfs calls
    _class=$(ctx_get ${_pfx}CLASS)

    # Common/aggragated data necessary for efficient resolution of snapshot names/commands
    if [ "$TTL" ] ; then
        query_onjails                     # Sets global ONJAILS
        query_onvms                       # Sets global ONVMS
        _suffix=$(calculate_snap_suffix)  # "@<name>" to append to the snapshot
        _autosnaps=$(query_param_values AUTOSNAP | grep 'true' | awk '{print $1}')
    fi
    if [ "$DESTROY" ] ; then
        query_zfs_recursive_defaults -s   # Set global SNAPSHOTS. Prevents repeat/excess zfs calls
        query_qconf_cells_and_paths       # Make sure globals are set: $CELLS and $CELLS_QPATHS
        SNAPSHOTS=$(echo "$SNAPSHOTS" | awk '$8 ~ /^[0-9]+[smHDWY]$/')
    fi

    # More efficient to run a single loop, than two separate loops for TTL vs DESTROY.
    # We can't trust that all dsets/snaps were queried with `query_zfs_recursive_defaults`.
    # Must loop over all cells. Will grep cached globals, and fallback to zfs when necessary.
    for _cell in $CELLS host ; do

        # Acquire the dataset data for each cell.
        ctx_bootstrap_cell $_cell $_pfx || continue
        [ "$(ctx_get ${_pfx}R_MNT)" ] && _r_dset=$(ctx_get ${_pfx}R_DSET)
        [ "$(ctx_get ${_pfx}P_MNT)" ] && _p_dset=$(ctx_get ${_pfx}P_DSET)

        # Cell should be autosnap; and not a running rootenv (could cause partial/inconsistent state
        echo "$_autosnaps" | grep -Eqs "^$_cell\$" || continue
        [ -z "${_class##root*}" ] && is_cell_running $_cell && continue

        # If root/persist (_r/_p) dataset was found, the add it to the snaps list
        if [ "$TTL" ] ; then
            [ "$_r_dset" ] && _r_snaps="${_r_snaps} $_r_dset@$_suffix"
            [ "$_p_dset" ] && _p_snaps="${_p_snaps} $_p_dset@$_suffix"
        fi

        # Compose the destroy commands while inside the loop
        [ "$DESTROY" ] && append_compose _CMDS compose_thin_old_snaps_cmds

        unset _r_dset _p_dset # Keep the variables clean
    done

    # Spaces in the snaps assignment loop, even if there are no snaps could be non-zero but blank
    is_blank "$_r_snaps" || append _CMDS "zfs snapshot -o qb:ttl=${TTL} $_r_snaps"
    is_blank "$_p_snaps" || append _CMDS "zfs snapshot -o qb:ttl=${TTL} $_p_snaps"

    emit_cmds "$_CMDS"
}


main() {
    local _fn="main"

    parse_args "$@" || eval $(THROW $?)

    _COMMANDS=$(compose_zfs_commands)

    execute_commands "$_COMMANDS" || eval $(THROW $?)

    return 0
}

main "$@" || FATAL
exit 0
