#!/bin/sh

. $QCOMMON

trap_init

parse_args() {
    local _fn="parse_args" _opts OPTARG OPTIND
    while getopts dhs: _opts ; do case $_opts in
        d) DESTROY=true ;;
        h) WARN usage ; cat $ERR ; exit 0 ;;
        s) TTL="$OPTARG" ; assert_optarg || eval $(THROW $?) ;;
        *) exit 1 ;;
    esac ; done ; shift $(( OPTIND - 1 ))

    # Must provide [-d] and/or [-t]
    [ -z "$DESTROY" ] && [ -z "$TTL" ] && eval $(THROW 4 $_fn)

    # Sanitize TTL
    [ "$TTL" ] && { assert_time_format "$TTL" || eval $(THROW $? ${_fn}_2) ;}

    # Convenience globals
    DATE=$(date +%s)
}

calculate_snap_suffix() {
    local _fn="calculate_snap_suffix" _date

    # Use the TTL timeframe for modifying the snapname
    case ${TTL##*[0-9]} in
        s) _date='+%b%d_%H%M' ;;
        m) _date='+%b%d_%H%M' ;;
        H) _date='+%b%d_%H_H' ;;
        D) _date='+%b%d_%H_D' ;;
        W) _date='+%b%d_%H_W' ;;
        M) _date='+%Y_%b%d_M' ;;
        Y) _date='+%Y_%b%d_Y' ;;
    esac
    echo $(date $_date)  # Snap will have this @name
}

calculate_destroy_date() {
    local _fn="calculate_destroy_date"

    case ${_ttl##*[0-9]} in
        s) _mult="1" ;;
        m) _mult="60" ;;
        H) _mult="3600" ;;
        D) _mult="3600*24" ;;
        W) _mult="3600*24*7" ;;
        M) _mult="3600*24*31" ;;
        Y) _mult="3600*24*365" ;;
        *) return 1 ;;
    esac
    echo "(${_ttl%?} * $_mult) + $_crea_unix" | bc  # Final destroy date in unix time
}

compose_new_snapshots_cmds() {
    local _fn="compose_new_snapshots_cmds" _r_snap _p_snap _zfs_r_cmd _zfs_p_cmd

    # Make sure the cell is flagged for autosnap, or return silently back to caller
    echo "$_autosnaps" | grep -Eqs "^$_cell\$" || return 1

    # Generate notional snap names
    [ "$_p_dset" ] && _p_snap="$_p_dset@$_suffix"
    [ "$_r_dset" ] && _r_snap="$_r_dset@$_suffix"

    # Don't snapshot running rootenv where updates/installs could cause partial/inconsistent state
    [ "${_class##root*}" ] && { echo_grep -q "$ONJAILS" "$_cell" \
        || echo_grep -q "$ONVMS" "$_cell" ;} && unset _r_snap

    # Update the primary _CMD. Note that the space in front of " $_r_snap" is required
    [ -z "$_CMD_R_SNAPSHOT" ] && _zfs_r_cmd="zfs snapshot -o qb:ttl=$TTL"
    [ -z "$_CMD_P_SNAPSHOT" ] && _zfs_p_cmd="zfs snapshot -o qb:ttl=$TTL"
    _CMD_R_SNAPSHOT="$(printf "%b" "$_zfs_r_cmd" "$_CMD_R_SNAPSHOT" " $_r_snap")"
    _CMD_P_SNAPSHOT="$(printf "%b" "$_zfs_p_cmd" "$_CMD_P_SNAPSHOT" " $_p_snap")"
}

compose_thin_old_snaps_cmds() {
    local _fn="compose_thin_old_snaps_cmds"
    local _rsnaps _psnaps _snapshots _snap _clones _ttl _integer _creation _crea_unix _destroy

    # Most _dsets should be found in SNAPSHOTS. Fallback to query_* if not found.
    _class=$(ctx_get ${_pfx}CLASS)
    if [ "$_r_dset" ] && [ "$_class" ] && [ -z ${_class##root*} ] ; then
        # Only rootenvs will have root-dataset snapshots
        _rsnaps=$(echo "$SNAPSHOTS" | grep -E "^$_r_dset@") \
            || _rsnaps=$(query_rootsnaps $_r_dset)
    fi
    # Even rootenvs typically have a persistent dataset. However, skip disp cells.
    if [ "$_p_dset" ] && [ "$_class" ] && [ -n "${_class#disp*}" ] ; then
        _psnaps=$(echo "$SNAPSHOTS" | grep -E "^$_p_dset@") \
            || _psnaps=$(query_persistsnaps $_p_dset)
    fi
    _snapshots="$(echo "$_rsnaps" ; echo "$_psnaps")"

    # Resolve each line's destroy date, and add to the list if old
    while IFS= read -r _line ; do
        [ -z "$_line" ] && continue   # Some lines are blank. Ignore/continue
        _snap=$(echo $_line | awk '{print $1}')
        _clones=$(echo $_line | awk '{print $9}')
        _ttl=$(echo $_line | awk '{print $8}')
        _creation=$(echo "$_line" | awk '{print $3, $4, $5, $6, $7}')
        _crea_unix=$(date -j -f "%a %b %d %H:%M %Y" "$_creation" +"%s")
        _destroy=$(calculate_destroy_date)

        # Final command addition. Mute the comparison to not pollute $ERR
        mute assert_int_comparison -G $_destroy -- $DATE && [ "$_clones" = "-" ] \
            && _CMD_DESTROY="$(printf "%b" "$_CMD_DESTROY\n" "hush zfs destroy $_snap")"
    done << EOF
$_snapshots
EOF
}

manage_composition_loop() {
    local _fn="manage_composition_loop" _class _autosnaps _suffix _r_dset _p_dset _pfx="t_"

    query_qconf_cells_and_paths     # Populate globals: $CELLS and $CELLS_QPATHS
    query_zfs_recursive_defaults    # Sets global DATASETS. Prevents repeat/excess zfs calls
    _class=$(ctx_get ${_pfx}CLASS)

    # Common/aggragated data necessary for efficient resolution of snapshot names/commands
    if [ "$TTL" ] ; then
        query_onjails                     # Sets global ONJAILS
        query_onvms                       # Sets global ONVMS
        _suffix=$(calculate_snap_suffix)  # "@<name>" to append to the snapshot
        _autosnaps=$(query_param_values AUTOSNAP | grep 'true' | awk '{print $1}')
    fi
    if [ "$DESTROY" ] ; then
        query_zfs_recursive_defaults -s   # Set global SNAPSHOTS. Prevents repeat/excess zfs calls
        query_qconf_cells_and_paths       # Make sure globals are set: $CELLS and $CELLS_QPATHS
        SNAPSHOTS=$(echo "$SNAPSHOTS" | awk '$8 ~ /^[0-9]+[smHDWY]$/')
    fi

    # More efficient to run a single loop, than two separate loops for TTL vs DESTROY.
    # We can't trust that all dsets/snaps were queried with `query_zfs_recursive_defaults`.
    # Must loop over all cells. Will grep cached globals, and fallback to zfs when necessary.
    for _cell in $CELLS host ; do

        # Acquire the dataset data for each cell.
        ctx_bootstrap_cell $_cell $_pfx || continue
        [ "$(ctx_get ${_pfx}R_MNT)" ] && _r_dset=$(ctx_get ${_pfx}R_DSET)
        [ "$(ctx_get ${_pfx}P_MNT)" ] && _p_dset=$(ctx_get ${_pfx}P_DSET)

        # Prepare the commands
        [ "$TTL" ] && compose_new_snapshots_cmds
        [ "$DESTROY" ] && compose_thin_old_snaps_cmds
        unset _r_dset _p_dset  # Keep the variables clean
    done
}


main() {
    local _fn="main"

    parse_args "$@" || eval $(THROW $?)
    manage_composition_loop

    _COMMANDS="_CMD_R_SNAPSHOT _CMD_P_SNAPSHOT _CMD_DESTROY"
    execute_commands "$_COMMANDS" || eval $(THROW $?)
    return 0
}

main "$@" || FATAL
exit 0
