#!/bin/sh

# Options and X11 window determine variables; incorporated by a single `eval` at the end

. $QUBSD

get_options() {
	while getopts d:ehHlL:Npqrs:tu:yxX opts ; do case $opts in
		d) _DPI="${OPTARG}" ;;
		e) _EPHM="true" ;;
		h) get_msg2 -eu ;;
		H) _HOSTX11="true" ;;
		l) _COMPAT="/compat/ubuntu" ;;
		L) _COMPAT="${OPTARG}" ;;
		N) _NORUN="true" ;;
		p) _POPUP="true" ;;
		q) _REDIRECT=' > /dev/null 2>&1 &' ; _REDIRECT2='-o /dev/null' ;;
		r) _USER="root" ;;
		s) _SHELL="${OPTARG}" ;;
		u) _USER="${OPTARG}" ;;
		y) _NOX11="true" ;;  # Option must come before [x|X] for proper checks
		x) _NEWWIND="true"  ; _X11="true" ; [ -n "$_NOX11" ] && get_msg2 -Em _e10  ;;
		X) _SAMEWIND="true" ; _X11="true" ; { [ -n "$_NOX11" ] || [ -n "$NEWWIND" ] ;} && get_msg2 -Em _e10 ;;
		*) exit 1 ;;
	esac  ;  done  ;  shift $(( OPTIND - 1 ))

	_JAIL="$1" ; shift
	_CMD="$@"
}

parse_jail_vars() {
	# If X is running, get the jailname of the active window, and note that host is X111
	if pgrep -q Xorg ; then
		[ -n "$_SAMEWIND" ] && _DISPLAY="env DISPLAY=:$(get_info -e _XSOCK)"
		get_info _XJAIL
		XORG_AVAIL='true'
	fi

	# Unless already specified, JAIL and USER should be set to the active window
	: "${_JAIL:=$_XJAIL}"
	: "${_USER:=$_JAIL}"

	# If [-p] popup was passed, create the popup and get the _CMD to be run
	[ "$_POPUP" ] \
		&& _CMD=$(create_popup -im "Enter command for $_JAIL\\\n${_USER}@${_JAIL}: # ")

	# Handle linux compat mods
	if [ -n "$_COMPAT" ] ; then
		_SHELL=${_SHELL:="/bin/bash"}   # Default to bash if user didnt specify a shell

		# Cleanup user specified compat in case the didnt include "/compat"
		! echo "$_COMPAT" | grep -qs "compat" && _COMPAT="/compat/${_COMPAT}"

		# Robust/resilient for various combos of _USER_CMD, including default if not included
		case "${_USER}_${_CMD}" in
			root_)  SHELL="/bin/bash" ; _CMDMOD='' ;;
			root_*) SHELL="/bin/bash" ; _CMDMOD="-c '$_CMD'" ;;
			*_)     SHELL="/bin/bash" ; _CMDMOD="-c 'su - $_USER'" ;;
			*_*)    SHELL="/bin/bash" ; _CMDMOD="-c 'su -c \"$_CMD\"' $_USER" ;;
		esac
	fi

	# Ensure default values if the user didnt specify them
	_shell=$(get_jail_shell -e "$_JAIL")        # Lib function orders shell priority
	_SHELL=${_SHELL:=$_shell}
	[ -z "$_X11" ] && : ${_CMD:="$SHELL"} || : ${_CMD:="xterm"}
}

create_ephmjail() {
	# Must reassign the _JAIL and _USER names to the ephm, for later commands to work properly
	[ "$_USER" = "$_JAIL" ] && _USER="EPHM-${_JAIL}" && cycle_user="true"
	_TEMPL_JAIL="$_JAIL"
	_JAIL="EPHM-${_JAIL}"

	_cycle=0
	while ! chk_avail_jailname -- "$_JAIL" ; do    # Find an available jail name
		_cycle=$(( _cycle + 1 ))
		_JAIL="${_JAIL}_${_cycle}"
		[ -n "$cycle_user" ] && _USER="${_USER}_${_cycle}"
	done

	get_msg2 -m _m4    # Inform user that it will take a moment to create/start the ephmjail

	# Create dispjail and disable the no_destroy protection
	if ! $QLEXEC/qb-create -y -p GATEWAY=none -p IPV4=none -p NO_DESTROY=false \
			-p AUTOSNAP=false -c dispjail -t $_TEMPL_JAIL $_JAIL > /dev/null 2>&1 ; then
		get_msg2 -Em _e11
	fi

	# Monitor for any EPHM ps TT that are open, with detached script. Will destroy EPHM after.
	export _JAIL
	daemon -t "Ephemeral: $_JAIL " -o /dev/null -- /bin/sh << 'EOF'
		. $QLIB/quBSD.sh
		get_global_variables
		monitor_ephmjail
EOF
}

chk_app_X11() {
	# Use libraries resolution to figure out if we're dealing with an X11 app

  export _cmd=$(echo "$_CMD" | awk '{print $1}')
	if [ -z "$_COMPAT" ] ; then
		# Have to use some gymnastics to be certain we're at the actual pkg name, not just the binary
		chroot "${M_QROOT}/${_JAIL}" /bin/sh -s << 'EOF'
			_pkg=$(which $_cmd | xargs pkg which -q)
			[ -z "$_pkg" ] && exit 3
			pkg info -d $_pkg | grep -Eqs 'libX11|libxcb|qt5|libgtk|gui|x11' && exit 0
EOF
		return $?
	else
		chroot "${M_QROOT}/${_JAIL}/${_COMPAT}" $_SHELL -s << 'EOF'
		ldd "$(which $_cmd 2>/dev/null)" 2>/dev/null | grep -Eqs 'libX11\.so|libxcb\.so' && exit 0
EOF
		return $?
	fi
}

prepare_and_launch_xephyr() {
	# Use the JID+_int to find a unique socket name
	jid=$(jls -j $_JAIL -n jid | sed "s/jid=//")
  _int=0
	while [ $_int -le 99 ] ; do
		display="${jid}${_int}"
		[ -e "/tmp/.X11-unix/X${display}" ] && _int=$(( _int + 1 )) || break
	done || get_msg2 -Em _e9           # Error and exit if nothing found

	# Apply a baseline Xresources
  _xresources="${M_ZUSR}/${_JAIL}/home/${_JAIL}/.Xresources"
	[ -f "$_xresources" ] || _xresources="${M_ZUSR}/0gui/home/0gui/.Xresources"
	[ -f "$_xresources" ] || _xresources="${HOME}/.Xresources"
	[ -f "$_xresources" ] || unset _xresources

	export QLIB QRUN _JAIL _USER _DPI display _xresources
	daemon -t "Xephyr: $display, Jail: $_JAIL, Command: $_CMD, " -o /dev/null -- /bin/sh << 'EOF'
		. $QLIB/quBSD.sh
		launch_xephyr
EOF
	sleep .2   # Give another moment for the env to load in Xephyr
	return 0
}

run_jail_command() {
	# Make sure the user has a home directory
	[ ! "$_USER" = "root" ] && [ ! -d "${M_QROOT}/${_JAIL}/home/${_USER}" ] \
		&& get_msg2 -Epm _e7

	# Prefer Xephyr, but ensure that: it's possible, and it wasnt rejected by user-options
	if [ "$XORG_AVAIL" = "true" ] && [ -z "$_NOX11" ] && [ -z "$_HOSTX11" ] ; then
		if mount | grep $_JAIL | grep -Eqs "/qubsd/${_JAIL}/tmp/\.X11-unix" ; then
			if [ -z "$_SAMEWIND" ] && { chk_app_X11 || [ -n "$_NEWWIND" ] ;} ; then
				prepare_and_launch_xephyr
				_DISPLAY="env DISPLAY=:$display"
				_X11="true"
			fi
		fi

	# Host .X11-unix Xorg socket (X0). User must explicitly flag dangerous option
	elif [ "$XORG_AVAIL" ] && [ -z "$_NOX11" ] && [ -n "$_HOSTX11" ] ; then
		# Make sure there's a nullfs mount to leverage
		grep -Ev "^[[:blank:]]*#" ${JCONF}/${_JAIL} | grep -qs "host_x11.conf" || get_msg2 -Em _e12

		# Set display as host root (usually :0) if the switch was given
		display=$(pgrep -fl Xorg | grep -Eo ":[0-9]+" | grep -Eo "[0-9]+")
		_DISPLAY="env DISPLAY=:$display"
		_X11="true"
		get_msg2 -m _m3
	fi

	# Run the jexec command 
	rm_errfiles	; trap - HUP INT TERM QUIT EXIT
	case "${_COMPAT}_${_X11}" in
		_)      eval "jexec -l -U $_USER $_JAIL /bin/sh -c '$_CMD'" $_REDIRECT ;;
		_true)  eval "jexec -l -U $_USER $_JAIL $_DISPLAY /bin/sh -c '$_CMD'" > /dev/null 2>&1 & ;;
		*_)     eval "jexec -l -U root   $_JAIL chroot $_COMPAT $_SHELL $_CMDMOD" $_REDIRECT ;;
		*_true) eval "jexec -l -U root   $_JAIL chroot $_COMPAT $_SHELL -c \
										'su -c \"$_DISPLAY $_CMD\" $_JAIL'" > /dev/null 2>&1 & ;;
	esac
}

connect_vm_session() {
	# Pull the qconf parameters for VM attachment
	get_jail_parameter -d TMUX $_JAIL || get_msg2 -Epm _e2 TMUX "$_JAIL"
	get_jail_parameter -d VNC  $_JAIL || get_msg2 -Epm _e2 VNC  "$_JAIL"

	# Handle the vnc viewer port
	if [ ! "$VNC" = "false" ] ; then
		# Sometimes it can take 5-15 secs for a VM to launch (if ppt is bad). Wait
		_count=0
		while ! _vmpid=$(pgrep -fx "bhyve: $_JAIL") ; do
			# Wait 3 secs before message, to avoid unnecesary clutter
			[ "$_count" = 3 ] && get_msg2 -m _m2
			[ "$_count" -gt 15 ] && get_msg2 -Epm _e3
			sleep 1 ; _count=$(( _count + 1 ))
		done

		# Launch vnc viewer
		_vncport=$(sockstat -P tcp \
							| sed -nE "s/.*bhyve[[:blank:]]+${_vmpid}.*\*:([[:digit:]]+).*/\1/p")

		if [ -z "$_vncport" ] ; then
			_novnc="true"
		else
			# Remove errfiles before permanent new program launches
			rm_errfiles ; trap - HUP INT TERM QUIT EXIT
			vncviewer 0.0.0.0:$_vncport > /dev/null 2>&1 &
		fi
	else
		_novnc="true"
	fi

	# Launch TMUX if available
	if [ "$TMUX" = "true" ] ; then
		# Remove errfiles before permanent new program launches
		rm_errfiles ; trap - HUP INT TERM QUIT EXIT
		! tmux attach -t $_JAIL && get_msg2 -Epm _e4
	else
		# Error message for nothing to connect to
		[ "$_novnc" ] && get_msg2 -Epm _e5
	fi
}

main() {
	parse_jail_vars

	# Launch host xterm. Replace current shell with new one (exec).
	[ "$_JAIL" = "host" ] && rm_errfiles && trap - HUP INT TERM QUIT EXIT && exec xterm

	if [ "$_NORUN" ] ; then
		get_msg2 -m _m1
		if chk_isvm "$_JAIL" ; then
			start_jail -n "$_JAIL" || get_msg2 -m _e6
		else
			echo "jexec -l -U $_USER $_JAIL $_SHELL -c '$_CMD'" $_REDIRECT
		fi
		exit 0
	fi

	# Ephemeral jails live for a short timeframe, then die when stopped or window is closed
	[ -n "$_EPHM" ] && create_ephmjail

	# Make sure the jail is running
	! start_jail "$_JAIL" && get_msg2 -Epm _enone
	if chk_isvm "$_JAIL" ; then
		connect_vm_session
	else
		run_jail_command		
	fi
}

get_global_variables

get_options "$@"

main

exit 0
