#!/bin/sh

# qb-edit hard THROWs on syntax failures (level 1), and soft THROWs on config/runtime failures.
# Syntax errors are a safety issue, but config errors are not. Thus [-F FORCE] may be used.

. $QCOMMON

trap_init

parse_args() {
    local _fn="parse_args" _opts OPTARG OPTIND
    while getopts c:d:DFhp:qV _opts ; do case $_opts in
        c) CELL="$OPTARG" ; assert_optarg || eval $(THROW $?) ;;
        d) DEFAULT="$OPTARG" ; assert_optarg || eval $(THROW $?) ;;
        D) DELETE="true" ;;
        F) FORCE="true" ;;
        h) WARN usage ; cat $ERR ; exit 0 ;;
        p) PARAM="$OPTARG" ; assert_optarg || eval $(THROW $?) ;;
        q) QUIET=true ;;
        V) TRACE=true ;;
        *) eval $(THROW 8 _generic "Invalid option") ;;
    esac ; done ; shift $(( OPTIND - 1 ))

    # Resolve user input assignments. Continuously shift so the next assignment is always in $1
    [ -z "$CELL" ] && [ -z "$DEFAULT" ] && [ "$1" ] && CELL="$1" && shift
    [ -z "$PARAM" ] && [ "$1" ] && PARAM="$1" && shift
    [ "$1" ] && VALUE="$1" && shift

    # Final checks on raw user options/args
    [ "$1" ] && eval $(THROW 4 extra_args)  # No args should remain. If there are assume user error
    [ "$CELL" ] || [ "$DEFAULT" ] || eval $(THROW 4 cell_missing)
    [ "$PARAM" ] || eval $(THROW 4 param_missing)
    [ -z "$DELETE" ] && [ -z "$VALUE" ] && eval $(THROW 4 value_missing $PARAM)

    # Sanitize CELL/DEFAULT
    if [ "$CELL" ] && [ "$DEFAULT" ] ; then
        eval $(THROW 4 mutual_exclusive)           # Cant be both CELL and DEFAULT
    elif [ "$CELL" = "host" ] ; then
        # Host is special case. Has file in $D_CELLS, but a small set of modifiable params
        echo_grep -qd , "$PARAMS_HOST" "$PARAM" || eval $(THROW 4 host $PARAMS_HOST)
        FILE=$D_CELLS/$CELL
    elif [ "$CELL" ] ; then
        assert_cellname $CELL || eval $(THROW $?)           # Sanitize user input
        TYPE=$(query_cell_type $CELL)                       # Used for PARAM sanitization
        FILE=$D_CELLS/$CELL                                 # CELL file to operate on
    elif [ "$DEFAULT" ] ; then
        assert_ptype $DEFAULT || eval $(THROW $? ptype)     # Sanitize user input
        TYPE=$(conv_to_upper $DEFAULT)                      # Used for PARAM sanitization
        FILE=$D_QCONF/defaults.$(conv_to_lower $TYPE).conf  # Defaults file to operate on
    fi

    # Sanitize PARAM
    PARAM=$(conv_to_upper "$PARAM")  # Standardize user input (user-friendly :upper/lower: input)
    assert_param $PARAM || eval $(THROW $?)        # Sanitize user input
    PTYPE=$(conv_to_upper $(query_param_type $PARAM))
    case $PTYPE in
        JAIL) [ "$TYPE" = "JAIL" ] || eval $(THROW 4 type $PARAM $PTYPE ${FILE##*/} $TYPE) ;;
        VM)   [ "$TYPE" = "VM" ]   || eval $(THROW 4 type $PARAM $PTYPE ${FILE##*/} $TYPE) ;;
    esac
    # Certain PARAMS are excluded from being defaults, either for safety or sensibility
    [ "$DEFAULT" ] && echo_grep -qd , "$PARAMS_EXCL_DEFAULT" "$PARAM" \
        && eval $(THROW 4 default_invalid $PARAM)

    # CLASS is a hard CELL requirement. Defaults are for convenience, not config/fallback guarantees
    if [ "$DELETE" ] ; then
        [ "$CELL" ] && [ "$PARAM" = "CLASS" ] && eval $(THROW 4 delete_class)
    else
        # Basic syntax validation of user inputs. Save the higher level checks for later
        eval $PARAM=\"$VALUE\"
        ctx_validate_params -l 1 -P $PARAM || eval $(THROW $?)  # Syntax validation
    fi

    return 0
}

# Repeat commands. DEL/ADD avoids potential syntax pollution inherent to sed search-and-replace.
_compose_del_param() {
    local _fn="compose_cmd_helper"
    _CMD_DEL="sed -i '' -E \"/^$PARAM=/d\" $FILE"
    return 0
}
_compose_add_param() {
    local _fn="compose_cmd_helper" _tmpfile
    make_tmp _tmpfile
    _CMD_ADD="{ cat $FILE ; echo $PARAM=\\\"$VALUE\\\" ;} | sort > $_tmpfile && mv $_tmpfile $FILE"
    return 0
}
# Putting this sed command into a variable would be escape-char hell. Offload to function
_CMD_jconf_mod() {
    sed -i '' -E "/^[[:blank:]]*$CELL[[:blank:]]*\{/a\\
	devfs_ruleset=\"$VALUE\"" $D_JAILS/$CELL   # Leading tab here is literal. Do not change
}

compose_delete() {
    local _fn="compose_delete" _old_val _def_type _badcells _err_msg _pfx=old_
    [ -z "$DELETE" ] && return 0   # No [-D] option, skip

    # Relevant, or potentially relevant variables
    ctx_load_file $FILE $_pfx
    _old_val=$(ctx_get ${_pfx}$PARAM)

    # Check that there's something to delete, and create the accompanying _CMD
    grep -Eqs "^$PARAM=" $FILE || eval $(THROW 4 delete_nothing $PARAM $FILE)
    _compose_del_param

    # PPT could have multiple values. If user gave VALUE, only delete that one, keep the others
    if [ "$PARAM" = "PPT" ] && [ "$VALUE" ] ; then
        _old_val="$(ctx_get ${_pfx}PPT)"
        VALUE=$(echo "$_old_val" | sed -E "s|[ ]*$VALUE[ ]*||")
        [ "$VALUE" ] && _compose_add_param
    else
        unset VALUE  # This is critical for the check later, as it depends on -z test
    fi

    # Loop over all relevant cells to verify that PARAM deletion wont bork cell configs
    _def_type=$(ctx_get DEF_$TYPE)
    [ -z "$CELL" ] && query_qconf_cells_and_paths   # Load global CELLS for loop
    for _cell in $CELL $CELLS ; do
        # Set the proposed new value of the dereferenced PARAM (usually blank). Source the
        # qubsd.conf files in the correct order, but not the actual file to be modified.
        eval $PARAM=\"$VALUE\"
        [ "$FILE" = "$DEF_BASE" ]       || . $DEF_BASE
        [ "$FILE" = "$_def_type" ]      || . $_def_type
        [ "$FILE" = "$D_CELLS/$_cell" ] || . $D_CELLS/$_cell

        # If there was a default/fallback value, it will be referenced by PARAM now
        if ! ctx_validate_params -l 3 -P $PARAM $_cell ; then
            # Store/print the ERR just once, and list all the cells with problems.
            # Assumption is that usually, a missing critical PARAM fails with the same ERR message
            _badcells=$(printf "%b" "  $_badcells\n$_cell")
            [ -z "$_err_msg" ] && _err_msg=$(cat $ERR | sed -E "s|^[ ]*||")
        fi
    done
    _badcells="$(echo "$_badcells" | tail -n+2)"  # Remove blank line at the top

    # THROW if there were errors (but clear ERR to avoid long list of repeat err msgs)
    if [ "$_err_msg" ] && [ "$FORCE" ] ; then
        clear_err && WARN deletion_errors "$_err_msg" $PARAM "$_badcells"
    elif [ "$_err_msg" ] && [ -z "$FORCE" ] ; then
        clear_err
        WARN deletion_errors "$_err_msg" $PARAM "$_badcells"
        eval $(THROW 4 use_force)
    fi
    return 0
}

compose_modify() {
    local _fn="compose_modify" _old_val _pfx=old_
    [ "$DELETE" ] && return 0   # [-D] implicitly means we're not modifying the qconf

    # Relevant, or potentially relevant variables
    ctx_load_file $FILE $_pfx
    _old_val=$(ctx_get ${_pfx}$PARAM)

    # Final validation
    [ "$_old_val" = "$VALUE" ] && eval $(THROW 4 no_change)
    unset RC                                       # Stale RC must not pollute ERR interception
    hush ctx_validate_params -l 3 -P $PARAM $CELL  # hush due to potential for blank/invalid CELL

    # Intercept ERR before THROW for msg enrichement. `case` allows future expansion if necessary
    case $RC in
        151) # Defaults should not receive CIDR IPV4.
            [ "$DEFAULT" ] && clear_err && WARN ipv4 ${FILE##*/}
            ;;
    esac

    # We THROW not only for hard failures, but even just WARNs
    is_path_exist -s "$ERR" && { [ "$FORCE" ] || eval $(THROW $? use_force) ;}

    # PARAMS that require special handling.
    case $PARAM in
        PPT) [ "$_old_val" ] && VALUE="$_old_val $VALUE" ;;  # If pre-existing PPT, just += $VALUE
        DEVFS_RULE)
            _CMD_JCONF_DEL="sed -i '' -E \"/.*devfs_ruleset=/d\" $D_JAILS/$CELL"
            _CMD_JCONF_ADD="_CMD_jconf_mod"
            ;;
    esac

    # Modify the QCONF
    _compose_del_param
    _compose_add_param
    return 0
}

compose_warn() {
    local _fn="compose_warn"
    if [ -s "$ERR" ] ; then
        _err="$(cat $ERR)" && clear_err
        WARN warning_header
        _CMD_WARN="cat \"$ERR\" ; echo \"$_err\""
    fi
}

main() {
    local _fn="main"

    parse_args "$@"  || eval $(THROW $?)
    compose_delete   || eval $(THROW $?)
    compose_modify   || eval $(THROW $?)
    compose_warn

    _COMMANDS="_CMD_DEL _CMD_ADD _CMD_JCONF_DEL _CMD_JCONF_ADD _CMD_WARN"
    execute_commands "$_COMMANDS" || eval $(THROW $?)
}

main "$@" || FATAL

exit 0
