#!/bin/sh

# quBSD model is sane defaults, easy correct paths, warn when dangerous. Thus, qb-edit sanitizes/
# THROWs bad input syntax, but only warns for bad config/topology. It does not provide default
# fallback guarantees for missing PARAMS. It would only be a false sense of security fallback
# anyways. However, qb-edit does warn when a deleted PARAM results in a cell with a missing PARAM.


### UNFINISHED WORK ###
# Add PARAM specific running-jail changes
# Add restarts where running-jail cant be changed
# devfs_rules change in the jconfs
# if [ $CELL ] ; then level2 (or 3?) validate full config after change and report it
# if [ $DELETE $DEFAULT ] ; then provide list of cells that no longer have a resolved value for that deleted PARAM
# PPT is unique in that, it could have a VALUE to be deleted, in which case surgery should be performed

. $QCOMMON

trap_init

parse_args() {
    local _fn="parse_args" _opts OPTARG OPTIND
    while getopts c:d:Dhp: _opts ; do case $_opts in
        c) CELL="$OPTARG" ; assert_optarg || eval $(THROW $?) ;;
        d) DEFAULT="$OPTARG" ; assert_optarg || eval $(THROW $?) ;;
        D) DELETE="true" ;;
        h) eval $(WARN usage) ; cat $ERR ; exit 0 ;;
        p) PARAM="$OPTARG" ; assert_optarg || eval $(THROW $?) ;;
        *) eval $(THROW 8 _generic "Invalid option") ;;
    esac ; done ; shift $(( OPTIND - 1 ))

    # Resolve user input assignments. Continuously shift so the next assignment is always in $1
    [ -z "$CELL" ] && [ -z "$DEFAULT" ] && [ "$1" ] && CELL="$1" && shift
    [ -z "$PARAM" ] && [ "$1" ] && PARAM="$1" && shift
    [ -z "$DELETE" ] && [ "$1" ] && VALUE="$1" && shift

    # Final checks on raw user options/args
    [ "$CELL" ] || [ "$DEFAULT" ] || eval $(THROW 4 cell_missing)
    [ "$PARAM" ] || eval $(THROW 4 param_missing)
    [ -z "$DELETE" ] && [ -z "$VALUE" ] && eval $(THROW 4 value_missing $PARAM)
    [ "$1" ] && eval $(THROW 4 extra_args)  # No args should remain. If there are assume user error

    # Sanitize CELL/DEFAULT
    if [ "$CELL" ] && [ "$DEFAULT" ] ; then
        eval $(THROW 4 mutual_exclusive)           # Cant be both CELL and DEFAULT
    elif [ "$CELL" ] ; then
        assert_cellname $CELL || eval $(THROW $?)  # Sanitize user input
        TYPE=$(query_cell_type $CELL)              # Needed later for PARAM sanitization
        FILE=$D_CELLS/$CELL                        # CELL file to operate on
    elif [ "$DEFAULT" ] ; then
        assert_ptype $DEFAULT || eval $(THROW $?)  # Sanitize user input
        DTYPE=$(conv_to_upper $DEFAULT)            # Needed later for PARAM sanitization
        FILE=$D_QCONF/defaults.$(conv_to_lower $DTYPE).conf  # Defaults file to operate on
    fi

    # Sanitize PARAM
    PARAM=$(conv_to_upper "$PARAM")  # Standardize user input (user-friendly :upper/lower: input)
    PTYPE=$(conv_to_upper $(query_param_type $PARAM))
    _type="${TYPE}$DTYPE"            # PTYPE=BASE can go anywhere. Otherwise types must align
    case $PTYPE in
        JAIL) [ "$_type" = "JAIL" ] || eval $(THROW 4 type $PARAM $PTYPE $FILE $_type) ;;
        VM)   [ "$_type" = "VM" ]   || eval $(THROW 4 type $PARAM $PTYPE $FILE $_type) ;;
    esac
    # Certain PARAMS are excluded from being defaults, either for safety or sensibility
    [ "$DEFAULT" ] && echo_grep -qd , "$PARAMS_EXCL_DEFAULT" "$PARAM" \
        && eval $(THROW 4 default_invalid $PARAM)

    # CLASS is a hard CELL requirement. Defaults are for convenience, not config/fallback guarantees
    [ "$DELETE" ] && [ "$CELL" ] && [ "$PARAM" = "CLASS" ] && eval $(THROW 4 delete_class)

    # Provide syntax assertion (level 1) that user-input PARAM is valid
    ctx_validate_params -l 1 -P $PARAM || eval $(THROW $?)

    return 0
}

# Repeat commands. DEL/ADD avoids potential syntax pollution inherent to sed search-and-replace.
_compose_del_param() {
    local _fn="compose_cmd_helper"
    _CMD_DEL="sed -i '' -E \"/^$PARAM=/d\" $1"
    return 0
}
_compose_add_param() {
    local _fn="compose_cmd_helper" _tmpfile
    make_tmp _tmpfile
    _CMD_ADD="{ cat $1 ; echo $PARAM=\"$VALUE\" ;} | sort > $_tmpfile && mv $_tmpfile $1"
    return 0
}
_compose_warnings_cmd() {
    local _fn="compose_warnings_cmd" _warnings
    _warnings=$(cat $ERR)
    clear_err
    _CMD_WARNINGS="echo \"WARNING: Potential issues due to changes\" ; echo \"$_warnings\"")
}

conduct_cells_param_reassessment() {
    local _fn="conduct_cells_param_reassessment"

}

_compose

compose_cmds() {
    local _fn="compose_cmds" _pfx=old_

    # Deletion is simplest, start here
    if [ "$DELETE" ] ; then
        grep -Eqs "^$PARAM=" $FILE || eval $(THROW 4 delete_nothing)
        _compose_del_param $FILE
        [ "$DEFAULT" ] && _conduct_cells_param_reassessment
        return 0
    fi

    # Provide final checks and warnings
    ctx_load_file $FILE $_pfx
    _old_val=$(ctx_get ${_pfx}$PARAM)
    [ "$_old_val" = "$VALUE" ] && eval $(THROW 4 no_change)
    ctx_validate_params -l 2 -P $PARAM $VALUE || _compose_warning_cmd

    _compose_del_param $FILE
    _compose_add_param $FILE
}

main() {
    local _fn="main"

    parse_args "$@"  || eval $(THROW $?)
    compose_cmds     || eval $(THROW $?)

    _COMMANDS="_CMD_DEL _CMD_ADD"
    execute_commands "$_COMMANDS" || eval $(THROW $?)
}

main "$@" || FATAL

exit 0
