#!/bin/sh

. $QUBSD

get_options() {
	while getopts cdhkt:u opts ; do case $opts in
		c) cron_down ; exit 0 ;;
		d) _CMD="down" ;;
		k) _CMD="kill" ;;
		h) get_msg2 -eu ;;
		t) TIMEOUT="$OPTARG" ;;
		u) [ -z "$_CMD" ] && _CMD="up" || get_msg2 -Eum _e1 ;;
		*) exit 1 ;;
   esac  ;  done  ;  shift $(( OPTIND - 1 ))

	TIMEOUT="${TIMEOUT:=300}"
	PF_PASS="$QETC/pf_pass.conf"
	PF_BLOCK="$QETC/pf.conf"
}

get_parameters() {
	# Did not specify an action
	[ -z "$_CMD" ] && get_msg2 -Eum _e2

	# Check validity of timeout provided
	chk_integer -g 0 -v "[-t <timeout>]" -- $TIMEOUT

	get_jail_parameter -d GATEWAY "host" || exit 1
}

connection_down() {
	# Find all epairs and destroy them.
	ifconfig -l | grep -o "epair[[:digit:]]*[a,b]" | xargs -I@ ifconfig @ destroy

	# Make sure all other interfaces have no IP addr, and are down (except loopback).
	for _intf in $(ifconfig -l | sed -E "s/lo[[:digit:]]+//g") ; do
		ifconfig $_intf -alias > /dev/null 2>&1
		ifconfig $_intf down
	done

	# Set pf.conf, which is simply: "block all"
	pfctl -f $PF_BLOCK 
}

cron_down() {
	for _tap in $(ifconfig -g tap) ; do
		ifconfig $_tap -alias > /dev/null 2>&1
		ifconfig $_tap down
	done
}

check_and_manage_connection() {
	# Check if connection is up (try twice just in case one is down)
	host freebsd.org > /dev/null 2>&1 && return 0
	host 0.CC.pool.ntp.org > /dev/null 2>&1 && return 0

	# Bring host back to a baseline state with no connection
	connection_down

	# Bring connection up
	connect_client_to_gateway -t EXT_IF "host" "$GATEWAY"
}

revert_connection() {
	# User opted out of the <timeout> feature
	[ "$TIMEOUT" -eq 0 ] && get_msg2 -em _w1

	# Wait the prescribed time
	sleep $TIMEOUT

	# Check that there aren't still `pkg` or `freebsd-update` commands being run
	while $(pgrep -qf '/usr/sbin/freebsd-update') || $(pgrep -q 'pkg') ; do
		sleep 10
	done

	# Change pf back to NTP (123) only 
	pfctl -f $PF_BLOCK 
	exit 0
}

main() {
	# Terminate any other instances of qb-hostnet that might be running (waiting for TIMEOUT)
	pkill -f '/bin/sh $QLEXEC/qb-hostnet'

	if [ "$_CMD" = "up" ] ; then
		# Start gateway, modify pf 
		start_jail "$GATEWAY" || get_msg2 -Em _e3
		check_and_manage_connection	
		pfctl -f $PF_PASS 
		# Loop until specified timeout, then revert connection
		revert_connection &
	elif [ "$_CMD" = "down" ] ; then
		# Set pf to the restrictive file
		pfctl -f $PF_BLOCK
	elif [ "$_CMD" = "kill" ] ; then
		# Set pf to the restrictive file
		connection_down
	fi
}

get_global_variables

get_options "$@"

get_parameters

main

exit 0

