#!/bin/sh

. $QCOMMON

trap_init

parse_args() {
    local _fn="parse_args" _opts OPTARG OPTIND _pos1 _pos2 _level
    while getopts c:hp:sz _opts ; do case $_opts in
        c) CELL="$OPTARG" ; assert_optarg || eval $(THROW $?) ;;
        h) WARN usage ; cat $ERR ; exit 0 ;;
        p) PARAM="$OPTARG" ; assert_optarg || eval $(THROW $?) ;;
        s) snaps="true" ;;
        z) zfs="true" ;;
        *) exit 1 ;;
    esac ; done ; shift $(( OPTIND - 1 ))
    _pos1="$1" ; _pos2="$2"

    # Be nice to the user and try to parse mix/matched options and positionals
    if [ "$CELL" ] && [ -z "$PARAM" ] ; then
        [ "$_pos1" ] && PARAM=$_pos1

    elif [ "$PARAM" ] && [ -z "$CELL" ] ; then
        [ "$_pos1" ] && CELL=$_pos1

    elif [ -z "$CELL" ] && [ -z "$PARAM" ] ; then
        [ "$_pos1" ] && CELL=$_pos1
        [ "$_pos2" ] && PARAM=$_pos2

        # Final attempt at parsing CELL vs PARAM when no option is passed
        if ! is_path_exist -f $D_CELLS/$CELL && [ -z "$PARAM" ] ; then
            echo_grep -qd , "$PARAMS_ALL" "$CELL" && PARAM=$CELL && unset CELL
        fi
    fi

    # Sanitize missing cell
    { [ "$snaps" ] || [ "$zfs" ] ;} && [ -z "$CELL" ] && eval $(THROW 4 blank_cell)

    # Validate CELL and/or PARAM
    [ "$CELL" ] && { _level=2 validate_cellname $CELL || eval $(THROW $?) ;}
    [ "$PARAM" ] && { assert_param $PARAM || eval $(THROW $?) ;}

    # Convert lower-case entered PARAM to upper (user-friendly)
    [ "$PARAM" ] && PARAM=$(conv_to_upper "$PARAM")
    return 0
}

retrieve_data() {
    local _fn="retrieve_data"

    # Uses globals: $non_defaults and $params for simplicity
    # If CELL, then we dont need to the full params list. Otherwise, params were requested
    if [ "$CELL" ] ; then
        ctx_bootstrap_cell $CELL
        non_defaults=$(grep -Eo "^.*=" $D_CELLS/$CELL | tr -d '=')
        [ "$snaps" ] && query_rootsnaps $R_DSET && query_persistsnaps $P_DSET
        [ "$zfs" ] && query_datasets "$R_DSET $P_DSET"
    else
        params=$(query_param_values $PARAM) || eval $(THROW $?)
    fi
    return 0
}

write_results() {
    local _fn="write_results" _param _val _results

    make_tmp RESULTS

    # Writing parameters (no cell) is easier, do them first
    if [ -z "$CELL" ] ; then
        echo "$params"   >> $RESULTS
        return 0
    fi

    #### The existence of $CELL is assumed now ###

    # For just a single param, there's room to print the snapshots too
    if [ "$PARAM" ] ; then
        _param=$(ctx_get $PARAM)
        echo "$CELL $PARAM $_param"                              >> $RESULTS
        [ "$zfs" ]   && echo "$DATASETS"                         >> $RESULTS
        [ "$snaps" ] && echo "$ROOTSNAPS"    | awk '{print $1}'  >> $RESULTS
        [ "$snaps" ] && echo "$PERSISTSNAPS" | awk '{print $1}'  >> $RESULTS
        return 0
    fi

    # All PARAMS + SNAPS can be quite long. If [-s], prioritize only snaps.
    if [ "$snaps" ] ; then
        [ "$zfs" ]   && echo "$DATASETS"                         >> $RESULTS
        [ "$snaps" ] && echo "$ROOTSNAPS"    | awk '{print $1}'  >> $RESULTS
        [ "$snaps" ] && echo "$PERSISTSNAPS" | awk '{print $1}'  >> $RESULTS
        return 0
    fi

    # Without PARAM specified and no snaps, assume user wants the full list
    local IFS=,
    for _param in $PARAMS_TYPE ; do
        _val=$(ctx_get $_param)

        # Make special notation of lines which source from the default, vs directly
        if echo_grep -q "$non_defaults" $_param ; then
            echo "$CELL $_param $_val"     >> $RESULTS
        else
            echo "#default $_param $_val"  >> $RESULTS
        fi
        _results=$(cat "$RESULTS" | sort)
        echo "$_results" > $RESULTS
    done

    # There's always room to print the zfs datasets at the bottom
    [ "$zfs" ] && echo "$DATASETS"  >> $RESULTS
    return 0
}

main() {
    local _fn="main"

    parse_args "$@" || eval $(THROW $?)
    retrieve_data   || eval $(THROW $?)
    write_results
    cat $RESULTS | sort | column -t
}

main "$@" || FATAL
exit 0
