#!/bin/sh

### NOTES ON PROBLEMS STILL
# IPV4 is being chopped down due to defaults files chopping (the grep). Need better sophistication there
# with [-p] PARAM you should list ALL cells of the same type (noting the default value), not just the defaults themselves

. $QCOMMON

trap_init

parse_args() {
    local _fn="parse_args" _opts _pos1 _pos2
    while getopts :c:hp:sz _opts ; do
        case $_opts in
            c) CELL="$OPTARG" ;;
            h) eval $(WARN usage) ; cat $ERR ; exit 0 ;;
            p) PARAM="$OPTARG" ;;
            s) snaps="true" ;;
            z) zfs="true" ;;
            *) eval $(THROW 8 _generic "Invalid option") ;;
        esac
    done ; shift $(( OPTIND - 1 ))
    _pos1="$1" ; _pos2="$2"

    # Be nice to the user and try to parse mix/matched options and positionals
    if [ "$CELL" ] && [ -z "$PARAM" ] ; then
        [ "$_pos1" ] && PARAM=$_pos1

    elif [ "$PARAM" ] && [ -z "$CELL" ] ; then
        [ "$_pos1" ] && CELL=$_pos1

    elif [ -z "$CELL" ] && [ -z "$PARAM" ] ; then
        [ "$_pos1" ] && CELL=$_pos1
        [ "$_pos2" ] && PARAM=$_pos2

        # Final attempt at parsing CELL vs PARAM when no option is passed
        if ! is_path_exist -f $D_CELLS/$CELL && [ -z "$PARAM" ] ; then
            quiet echo_grep "$PARAMS_BASE $PARAMS_JAIL $PARAMS_VM" $CELL \
                && PARAM=$CELL && unset CELL
        fi
    fi

    # Sanitize missing cell
    { [ "$snaps" ] || [ "$zfs" ] ;} && [ -z "$CELL" ] && eval $(THROW 4 missing_cell)

    # Convert lower-case entered PARAM to upper (user-friendly)
    [ "$PARAM" ] && PARAM=$(echo "$PARAM" | tr '[:lower:]' '[:upper:]')
    return 0
}

retrieve_data() {
    local _fn="retrieve_data" _param_type _cells_files _defaults_files

    # Cell retrieval has less work than parameter
    if [ "$CELL" ] ; then
        hush ctx_bootstrap_cell $CELL
        non_defaults=$(grep -Eo "^.*=" $D_CELLS/$CELL | tr -d '=')
        [ "$snaps" ] && query_rootsnaps $R_DSET && query_persistsnaps $P_DSET
        [ "$zfs" ] && query_datasets "$R_DSET $P_DSET"
        return 0
    fi

    # All cells, in a single line
    _cells_files=$(ls -1 $D_CELLS | tr '\n' ' ' | sed "s|^|$D_CELLS/|; s| | $D_CELLS/|g")

    # Define which files should be searched for the defaults
    _param_type=$(query_param_type $PARAM) || eval $(THROW $?)
    case $_param_type in
        base) _defaults_files="$DEF_BASE $DEF_JAIL $DEF_VM" ;;
        jail) _defaults_files="$DEF_BASE $DEF_JAIL" ;;
        vm)   _defaults_files="$DEF_BASE $DEF_VM" ;;
    esac

    # These variables allow for later separation regarding which PARAMS are default values
    defaults=$(grep -E "^$PARAM=" $_defaults_files \
              | sed -E "s|.*/||" | tr -d '"' | tr '=:' ' ' | sed -E 's/.conf//')
    params=$(grep -E "^$PARAM=" $_cells_files | sed -E "s|^$D_CELLS/||" | tr -d '"' | tr '=:' ' ')
}

write_results() {
    local _fn="write_results" _param _val _results

    make_tmp RESULTS

    # Writing parameters (no cell) is easier, do them first
    if [ -z "$CELL" ] ; then
        echo "$defaults" >> $RESULTS
        echo "$params"   >> $RESULTS
        return 0
    fi

    #### The existence of $CELL is assumed now ###

    # For just a single param, there's room to print the snapshots too
    if [ "$PARAM" ] ; then
        _param=$(ctx_get $PARAM)
        echo "$CELL $PARAM $_param"                              >> $RESULTS
        [ "$zfs" ]   && echo "$DATASETS"                         >> $RESULTS
        [ "$snaps" ] && echo "$ROOTSNAPS"    | awk '{print $1}'  >> $RESULTS
        [ "$snaps" ] && echo "$PERSISTSNAPS" | awk '{print $1}'  >> $RESULTS
        return 0
    fi

    # All PARAMS + SNAPS can be quite long. If [-s], prioritize only snaps.
    if [ "$snaps" ] ; then
        [ "$zfs" ]   && echo "$DATASETS"                         >> $RESULTS
        [ "$snaps" ] && echo "$ROOTSNAPS"    | awk '{print $1}'  >> $RESULTS
        [ "$snaps" ] && echo "$PERSISTSNAPS" | awk '{print $1}'  >> $RESULTS
        return 0
    fi

    # Without PARAM specified and no snaps, assume user wants the full list
    for _param in $PARAMS_TYPE ; do
        _val=$(ctx_get $_param)

        # Make special notation of lines which source from the default, vs directly
        if quiet echo_grep "$non_defaults" $_param ; then
            echo "$CELL $_param $_val"     >> $RESULTS
        else
            echo "#default $_param $_val"  >> $RESULTS
        fi
        _results=$(cat "$RESULTS" | sort)
        echo "$_results" > $RESULTS
    done

    # There's always room to print the zfs datasets at the bottom
    [ "$zfs" ] && echo "$DATASETS"  >> $RESULTS
    return 0
}

main() {
    local _fn="main"

    parse_args "$@" || eval $(THROW $?)
    retrieve_data   || eval $(THROW $?)
    write_results

    cat $RESULTS | column -t
}

main "$@" || FATAL
exit 0
