#!/bin/sh

# Starts bhyve virtual machine with PCI passthrough for nicvm at pci0:68:0:0 
# Virtual interface on tap0 for connectivity 

# REQUIRE: netif jail

. /etc/rc.subr

name="autostart_jails"
desc="Automatically starts jails tagged in jailmap.conf"
rcvar="${name}_enable"
start_cmd="${name}_start"

autostart_jails_start() {
	JMAP="/usr/local/etc/quBSD/jailmap.conf"
	AUTOSTART=$(grep -E "autostart[[:blank:]]+true" $JMAP | awk '{print $1}')

	for jails in $AUTOSTART ; do
		jails -c $jails >> /root/loglog
	done
}

load_rc_config $name
run_rc_command "$1"

