#!/bin/sh

# PROVIDE: qb_cleanup
# REQUIRE: jail
# KEYWORD: shutdown

. /etc/rc.subr
. /usr/local/lib/quBSD/quBSD.sh

name="qb_cleanup"
desc="Cleans up lingering pieces of quBSD at boot/poweroff"
rcvar="${name}_enable"
start_cmd="${name}_start"

qb_cleanup_start() {

	# Source the global variables
	get_global_variables

	# Dont need the trap set by get_global_variables, coz we're removing /tmp/qubsd
	trap '' HUP INT TERM QUIT EXIT

	cleanup_files

	cleanup_disps
}

cleanup_files() {
	# Remove and replace the quBSD /tmp directory
	rm -r /tmp/quBSD > /dev/null 2>&1
	mkdir /tmp/quBSD > /dev/null 2>&1

	# Empty the contents of the quBSD log directory
	rm -r $(dirname $QBLOG) > /dev/null 2>&1
	
	# Make sure the directory exists
	mkdir -p $(dirname $QBLOG) > /dev/null 2>&1
}

cleanup_disps() {

	# Unmount EPHM datasets which may still be mounted
	for _mount in $(mount | awk '/EPHM/ {print $3}') ; do
		umount -f $_mount
	done

	# Remove lingering EPHM datasets in qubsd's zroot
	for _ephm in $(zfs list -Hro name "$R_ZFS" | grep "${R_ZFS}/EPHM-") ; do
		zfs destroy -rRf $_ephm > /dev/null 2>&1
	done

	# Remove lingering EPHM datasets in qubsd's zusr
	for _ephm in $(zfs list -Hrt all -o name "$U_ZFS" | grep -i "ephm") ; do
		zfs destroy -rRf $_ephm > /dev/null 2>&1
	done

	# Remove anything that starts with ^EPHM in qmap and jail.conf
   sed -i '' -E "/^EPHM/d" $QMAP
	sed -i '' -E "/^EPHM.*(\{|[[:blank:]])/,/^}/d" $JCONF
}

qb_cleanup_stop() {
	qb_cleanup_start
}

load_rc_config $name
run_rc_command "$1"

