#!/bin/sh

# Starts bhyve virtual machine with pci passthrough for pci0:71:0:1 and pci0:71:0:3
# Virtual interface on tap1 for connectivity

# PROVIDE: usbvm 
# REQUIRE: netif jail

. /etc/rc.subr

name="usbvm"
desc="Starts bhyve VM for usb virtual machine with virtual interface to isolate flash devices"
rcvar="${name}_enable"
start_cmd="${name}_start"
stop_cmd="${name}_stop"
stop_cmd="${name}_stop"
statys_cmd="${name}_status"

usbvm_start() {
	bhyveload -c stdio -m 1G -d /dev/zvol/zroot/usbvm -S usbvm > /dev/null 2>&1

	bhyve -c 1 -m 1G -H -A -P -S \
        	-s 0:0,hostbridge \
        	-s 1:0,lpc \
        	-s 2:0,virtio-net,tap1 \
        	-s 3:0,virtio-blk,/dev/zvol/zroot/usbvm \
        	-s 4:0,passthru,71/0/1 \
        	-s 5:0,passthru,71/0/3 \
        	usbvm > /dev/null 2>&1 &

}

usbvm_stop() {
	pkill -f 'bhyve: usbvm'	
}


load_rc_config $name
run_rc_command "$1"

