#!/bin/sh

# Starts bhyve virtual machine with pci passthrough for usbvm
# Virtual interface on tap1 for connectivity

# PROVIDE: usbvm 
# REQUIRE: netif jail

. /etc/rc.subr

name="usbvm"
desc="Starts bhyve VM for usb virtual machine with virtual interface to isolate flash devices"
rcvar="${name}_enable"
start_cmd="${name}_start"
stop_cmd="${name}_stop"
stop_cmd="${name}_stop"
statys_cmd="${name}_status"

usbvm_start() {
	ppt_usb1=$(sed -nE "s:ppt_usb1[[:blank:]]+:: p" /usr/local/etc/jail.conf.d/quBSD.conf)
	ppt_usb2=$(sed -nE "s:ppt_usb2[[:blank:]]+:: p" /usr/local/etc/jail.conf.d/quBSD.conf)
	zroot=$(sed -nE "s:quBSD_root[[:blank:]]+::p" /usr/local/etc/jail.conf.d/quBSD.conf)

	bhyveload -c stdio -m 1G -d /dev/zvol/${zroot}/usbvm -S usbvm > /dev/null 2>&1 

	if [ "$ppt_usb1" -a "$ppt_usb2" ] ; then
		bhyve -c 1 -m 1G -H -A -P -S \
    		    	-s 0:0,hostbridge \
    		    	-s 1:0,lpc \
        		-s 2:0,virtio-net,tap1 \
        		-s 3:0,virtio-blk,/dev/zvol/${zroot}/usbvm \
        		-s 4:0,passthru,"$ppt_usb1" \
        		-s 5:0,passthru,"$ppt_usb2" \
        		usbvm > /dev/null 2>&1 &
	
	elif [ -z "$ppt_usb1" -a -z "$ppt_usb2" ] ; then
		exit 1

	else
		bhyve -c 1 -m 1G -H -A -P -S \
    		    	-s 0:0,hostbridge \
    		    	-s 1:0,lpc \
        		-s 2:0,virtio-net,tap1 \
        		-s 3:0,virtio-blk,/dev/zvol/${zroot}/usbvm \
        		-s 4:0,passthru,"${ppt_usb1}${ppt_usb2}" \
        		usbvm > /dev/null 2>&1 &
	fi
}

usbvm_stop() {
	pkill -f 'bhyve: usbvm'	
}


load_rc_config $name
run_rc_command "$1"

