#!/bin/sh

# PROVIDE: qubsd-init
# BEFORE: FILESYSTEMS
# REQUIRE: zfs zvol

. /etc/rc.subr

name="qubsd_init"
desc="Ensures /zusr datasets are imported/mounted, and /overlay files symlinked"
rcvar="${name}_enable"
start_cmd="${name}_start"

qubsd_init_start() {
  zpool list zusr > /dev/null 2>&1 || zpool import -f zusr

  for _file in $(find "/overlay" -type f | sed "s:/overlay::") ; do

    if [ -d "$(dirname $_file)" ] ; then
      chflags noschg "$(dirname $_file)"
      [ -e "$_file" ] && chflags noschg $_file

    else
      mkdir -p $(dirname $_file)
    fi

    ln -sf /overlay${_file} $_file
  done

}

load_rc_config $name
run_rc_command "$1"
