#!/bin/sh

. /usr/local/lib/quBSD/quBSD.sh

get_parameters() {
	JAIL="$1"

	# Get jail parameters.
	get_jail_parameter CLASS   "$JAIL" || get_msg2 -Em _e
	get_jail_parameter ROOTENV "$JAIL" || get_msg2 -Em _e
}

main() {
	# Manual umount. Cant reference fstab in jail.conf (it might be inside encrypted dataset)
	umount -aF ${M_ZUSR}/${JAIL}/rw/etc/fstab > /dev/null 2>&1

	# Search for any lingering mounts, and remove them as well
	JMOUNT=$(mount | egrep -o "${M_QROOT}/${JAIL}/[^[:blank:]]+")
	[ -n "$JMOUNT" ] && echo "$JMOUNT" | xargs umount -f

	case $CLASS in
		appjail|cjail)
         # Reclone the root filesystem for JAIL
			reclone_zroot "$JAIL" "$ROOTENV" || get_msg2 -Em _e2 "$JAIL" "$ROOTENV"
		;;
		dispjail)
         # Reclone the root filesystem for JAIL
			reclone_zroot "$JAIL" "$ROOTENV" || get_msg2 -Em _e2 "$JAIL" "$ROOTENV"

			# Dispjails also reclone the zusr portion from template (if it exists)
			get_jail_parameter -d TEMPLATE "$JAIL" || get_msg2 -Em _e
			chk_valid_zfs "${U_ZFS}/${TEMPLATE}" && ! reclone_zusr "$JAIL" "$TEMPLATE" \
				&& get_msg2 -Em _e3 "$JAIL" "$ROOTENV"
		;;
		rootjail)
			# Rootenv flags stay down for convenience, but can be long op. fork and silence 
			[ -e ${M_QROOT}/${JAIL} ] && (exec chflags -R noschg ${M_QROOT}/${JAIL} > /dev/null 2>&1)
	esac

	# Flags come down after stopping, but fork process and silence, to reduce user lag
	[ -e ${M_ZUSR}/${JAIL} ] && (exec chflags -R noschg ${M_ZUSR}/${JAIL} > /dev/null 2>&1)

	# Re-encrypt the dataset, if applicable
	[ ! "$(zfs list -Ho encryption ${U_ZFS}/${JAIL})" = "off" ] \
		&& zfs umount -u ${U_ZFS}/${JAIL}

	return 0
}

get_global_variables

get_parameters "$@"

main

exit 0
