#!/bin/sh

. /usr/local/lib/quBSD/quBSD.sh

get_options() {
	JAIL="$1"
	get_jail_parameter -dqs CLASS   "$JAIL" || get_msg2 -m _e
	get_jail_parameter -d   CONTROL "$JAIL" || get_msg2 -Em _e
	get_jail_parameter -d   GATEWAY "$JAIL" || get_msg2 -Em _e
}

main() {
	# First establish connections to the upstream gateway and control jail
	connect_client_to_gateway -d "$JAIL" "$GATEWAY"
	connect_client_to_gateway -dt SSH "$JAIL" "$CONTROL"

	# If this jail is also a gateway, connect it to downstream clients.
	for _cli in $(get_info -e _CLIENTS "$JAIL") ; do
		chk_isrunning "$_cli" && connect_client_to_gateway "$_cli" "$JAIL"
	done

	# If this is a cjail, check all the onjails to see if this is their control jail. 
	if [ "$CLASS" = "cjail" ] ; then 
		for _onj in $(get_info -e _ONJAILS | grep -v $JAIL) ; do
			# Does _onj have an explicit cjail in QCONF? If not, is $JAIL the QCONF #default? 
			! grep -Eqs "^${_onj}[[:blank:]]+CONTROL[[:blank:]]+${JAIL}" $QCONF \
				&& ! grep -Eqs "^${_onj}[[:blank:]]+CONTROL[[:blank:]]+"  $QCONF \
				&& ! grep -Eqs "^#default[[:blank:]]+CONTROL[[:blank:]]+${JAIL}" $QCONF \
				&& continue			
			connect_client_to_gateway -t SSH "$_onj" "$JAIL"
		done
	fi
}


get_global_variables

get_options "$@"

main

exit 0

