#!/bin/sh
# /usr/local/bin/qubsd-dhcp

# Unifed script for jails and FreeBSD VMs. Monitors for new interfaces tagged with DHCPD

write_dhclient_conf() {
# There is little reason to renegotiate frequently, so timeout is set high.
# Lowest possible backoff. These are internal virtual intf connections.
cat << EOF
timeout 21600;
retry 1;
initial-interval 1;
backoff-cutoff 1;
EOF
}

main() {
    # Write aggressive dhclient settings
    write_dhclient_conf > /tmp/qubsd_dhclient.conf

    # Monitor for new interfaces that appear as ifconfig group DHCPD
    while [ -f "$pidfile" ] ; do
        for _intf in $(ifconfig -g "QB-DHCPD") ; do
            pgrep -qfl "dhclient.*$_intf" || dhclient -bc /tmp/qubsd_dhclient.conf $_intf

            # Prevents collisions/races from rapid-fire dhclient invocation (can lockup resolv.conf)
            sleep 1
        done
        sleep 2
    done
}

pidfile="$1"

main

exit 0
