#!/bin/sh

# PROVIDE: qubsd-init
# BEFORE: FILESYSTEMS
# REQUIRE: zfs zvol

. /etc/rc.subr

name="qubsd_init"
desc="Ensures /zusr datasets are imported/mounted, and /overlay files symlinked"
rcvar="${name}_enable"
start_cmd="${name}_start"

qubsd_init_start() {

	# Make sure that the pool is imported
	if ! zpool list zusr > /dev/null 2>&1 ; then 
		zpool import -f zusr || return 0
	fi

	# Better to check-then-load than risk boot failure with a failed fstab entry
	sysctl dev.virtio_p9fs | grep -Eqs "xfer" && mount -t p9fs xfer /xfer
	
	# Link all the files in overlay to their respective host locations
	for _file in $(find "/zusr/overlay" -type f | sed "s:/zusr/overlay::") ; do
		[ -d "$(dirname $_file)" ] || mkdir -p $(dirname $_file)
		ln -sf /zusr/overlay${_file} $_file
	done
	
	# Mount /zusr/home. If no passwd file, assume all directories are pw users
	if [ -d "/zusr/home" ] ; then
		mount_nullfs /zusr/home /home

		# Only create the users if there isnt a dedicated pw file
		if [ ! -e "/zusr/overlay/etc/master.passwd" ] ; then
			for _user in $(find "/home" -type d | sed "s:/home/::") ; do
				pw useradd -n $_user -d /home/$_user -s /bin/csh -m
			done
		fi
	fi

	# SIGALRM forces an rc config reload, which now has the symlinked rc.conf.local
	kill -ALRM $RC_PID
}

load_rc_config $name
run_rc_command "$1"
