#!/bin/sh
# /usr/local/etc/X11/bspwmrc

# Set all border widths to 0 pixels.
bspc config border_width 0

# Set the gap between windows to 0 pixels.
bspc config window_gap 0

# Optional: Set gaps around the monitor/screen to 0 as well.
bspc config top_padding    0
bspc config bottom_padding 0
bspc config left_padding   0
bspc config right_padding  0
