#!/bin/sh

# PROVIDE: qb_vmboot
# REQUIRE: netif jail

. /etc/rc.subr

name="qb_vmboot"
desc="Calls the VM startup script at /vmusr/.quBSD/vm-local.rc"
rcvar="${name}_enable"
start_cmd="${name}_start"

qb_vmboot_start() {
  zpool list vmusr > /dev/null 2>&1 || zpool import -f vmusr
  /bin/sh /vmusr/.quBSD/vm-rc.local > /dev/null 2>&1 &
}

load_rc_config $name
run_rc_command "$1"
